- name: Create Secret with MySQL credentials
  community.kubernetes.k8s:
     definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
            name: db-config
            namespace: '{{ ansible_operator_meta.namespace }}'
        data:
          host: mysql
          name: test
	      
