- name: Create Secret with MySQL credentials
  community.kubernetes.k8s:
     definition:
        apiVersion: v1
        kind: Secret
        metadata:
            name: db-admin
            namespace: '{{ ansible_operator_meta.namespace }}'
        data:
          password: YWRtaW4xMjM=
	      
