- name: Create Secret with MySQL credentials
  community.kubernetes.k8s:
     definition:
        kind: Secret
        apiVersion: v1
        metadata:
          name:  mysql-secret
          namespace: '{{ ansible_operator_meta.namespace }}'
        type: Opaque
        stringData:   # We dont need to worry about converting to base64
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_DATABASE: fullstack_api
          MYSQL_ROOT_PASSWORD: password

          DB_HOST: fullstack-mysql
          DB_DRIVER: mysql
          API_SECRET: 98hbun98h 
          DB_USER: admin
          DB_PASSWORD: admin
          DB_NAME: fullstack_api
