- name: Create Postgres Service
  community.kubernetes.k8s:
     definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: postgres
          namespace: '{{ ansible_operator_meta.namespace }}'
        spec:
          type: NodePort
          ports:
            - port: 5432
              targetPort: 5432
              nodePort: 30100
        selector:
          app: postgres
